sudo: false
language: node_js
node_js:
 - node
 - 7
services:
 - mongodb
before_install:
 - npm install jspm
 - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
install: npm install && jspm install
before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 # jspm install makes some changes that break the Karma tests, revert these
 - git checkout app/client/config.js
script: grunt testCoverage
after_success: grunt uploadCoverage; grunt jshint
addons:
  firefox: latest
env:
  global:
    # JSPM_GITHUB_AUTH_TOKEN
    secure: OpFT/zzEX8D00IkQntYyFPgaD5Azu58089zbbLVtXvvD7/R1ABWMpp2YjhxrdSFzU2Dedjk/mAtQSj/3a65nbmi99BMEQAFYNvpR/A0GjcLLNwx9PNktxdWBN/0/qd3Mvdo3AlidQwbj+MB4KhFLh4QFTyB1ExnO+V2QIHzN9hgpBm/rQr9qw4uv6ny/yc21pNLdk71nXiaA75a77KBY0mOQr6C4C51f/HrDgsm2lWUVWuJZIE0i4fetuSe3Lu9VhmbGBN7k8oK/xPWxERJhMQx9uNLcDN21pnPsUOGKfA5qCjHEqa2FnqNPnAFpxZvdH8c6ND1pcuuAmEjdN1d75+3iIGDtLjYDvWKCJGKD0YnOUe4csEB2Ns4VWVq4pkjv0HislkgyYJKwzuwr+y9W7pYKe5UkuW579FdVunHpwRZKmL15KRf9gI37b0jjn8vA0tFCCBxUVUldAhEQ5XBti/ictJAg9nk5OFMhFi69EACOkxJawSAgoyv1s2005DeAsAwwSJFfH5tohvo1EGtwQXKcoXoTw4aGxCEKeCY4ZXwp+OnTxgvlzwVQiR021v/rgtLPCxDog8NAmvnk6L60/M/F2+nxaE4UjlvoY0wYW/8fgRol3BQqH2l/Lmmt5AgZNCnKL0V6ekNLb6YebMIPIQGcWgCg1is0UCi9gaIgXYI=
